id: ICFAB5D4B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T08:41:04+00:00'
last_modified: '2022-06-08T09:15:17.113028+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27314
  title: བོད་ལྗོངས་ཀྱི་ལོ་རྒྱུས་གོ་བབ་དཔྱད་ཞིབ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E268:
      image_group_id: I4313
      title: ''
      total_pages: 764
      order: 1
      base_file: E268.txt
    B0E8:
      image_group_id: I4314
      title: ''
      total_pages: 793
      order: 2
      base_file: B0E8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
